### ISSUE TITLE
Play Store shows app as a malware.

### ISSUE THREAD

**Issue by SinghCoder** [traccar/traccar-sms-gateway#11]
### DESCRIPTION

The Google Play Store on installing the app shows it as a trojan virus.

### STEPS

Install the app.

### EXPECTED

It should show app as safe.

### OBSERVATIONS

![trojan](https://user-images.githubusercontent.com/32142363/147737978-e95548a3-121d-4811-b6e5-1080d9fb8887.png)

**Comment by SinghCoder** [comment]
@moezbhatti

**Comment by SinghCoder** [comment]
@tananaev

**Comment by tananaev** [comment]
Google Play doesn't check for any malware on installation. Are you using Samsung device?

**Comment by SinghCoder** [comment]
It is Redmi Note 7 Pro.

**Comment by tananaev** [comment]
They probably have some vendor specific antivirus. You should submit a false positive ticket with them.
